filmweb/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='movies/')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path

from movies import views

urlpatterns = [
    path('', views.index, name='index'),
    path('films/', views.FilmListView.as_view(), name='film_list'),
    path('films/<int:pk>/', views.FilmDetailView.as_view(), name='film-detail'),
    path('films/genres/<str:genre_name>/', views.FilmListView.as_view(), name='film_genre'),
    path('topten', views.topten, name='topten'),
    path('film/create/', views.FilmCreateView.as_view(), name='film-create'),
    path('film/<int:pk>/update/', views.FilmUpdateView.as_view(), name='film-update'),
    path('film/<int:pk>/delete/', views.FilmDeleteView.as_view(), name='film-delete'),
]

movies/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.urls import reverse

""" Metoda vrací cestu k uploadovaným souborů - přílohám filmů.
    Cesta má obecnou podobu: film/id-filmu/attachments/nazev-souboru. 
    Parametr instance odkazuje na instanci (objekt) filmu.
    Parametr filename obsahuje název uploadovaného souboru. """
def attachment_path(instance, filename):
    return "film/" + str(instance.film.id) + "/attachments/" + filename

""" Metoda vrací cestu k uploadovanému plakátu. """
def poster_path(instance, filename):
    return "film/" + str(instance.id) + "/poster/" + filename


class Genre(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name="Genre name",
                            help_text='Enter a film genre (e.g. sci-fi, comedy)')

    class Meta:
        # atribut ordering definuje upřednostňovaný způsob řazení - zde vzestupně podle pole/sloupce name
        ordering = ["name"]

    def __str__(self):
        """ Řetězec, který se používá jako textová reprezentace objektu (například v administraci aplikace).
        V našem případě bude objekt (žánr) reprezentován výpisem obsahu pole name """
        return self.name

    def film_count(self, obj):
        return obj.film_set.count()


class Film(models.Model):
    # Fields
    # Znakové pole o maximální délce 200 znaků pro vložení názvu filmu
    title = models.CharField(max_length=200, verbose_name="Title")
    # Textové pole pro vložení delšího textu popisujícího děj filmu
    # Formulářový prvek může zůstat prázdný - parametry blank=True, null=True
    plot = models.TextField(blank=True, null=True, verbose_name="Plot")
    # Pole obsahuje datum uvedení filmu, které musí být zadáno v náležitém tvaru (YYYY-MM-DD); nepovinný údaj
    release_date = models.DateField(blank=True, null=True,
                                    help_text="Please use the following format: <em>YYYY-MM-DD</em>.",
                                    verbose_name="Release date")
    # Celočíselné pole pro nepovinné zadání stopáže (délky) filmu v minutách
    runtime = models.IntegerField(blank=True, null=True,
                                  help_text="Please enter an integer value (minutes)",
                                  verbose_name="Runtime")
    # Pole pro zadání desetinného čísla vyjadřujícího hodnocení filmu v rozsahu 1.0 až 10.0
    # Výchozí hodnota je nastavena na 5.0
    # K validaci hodnot jsou použity metody z balíku/knihovny django.core.validators
    rate = models.FloatField(default=5.0,
                             validators=[MinValueValidator(1.0), MaxValueValidator(10.0)],
                             null=True,
                             help_text="Please enter an float value (range 1.0 - 10.0)",
                             verbose_name="Rate")
    # Pole typu image, které umožňuje upload obrázku s plakátem filmu
    poster = models.ImageField(upload_to=poster_path, blank=True, null=True, verbose_name="Poster")
    # Vytvoří vztah mezi modely Film a Genre typu M:N
    genres = models.ManyToManyField(Genre, help_text='Select a genre for this film')

    # Metadata
    class Meta:
        # Záznamy budou řazeny primárně sestupně (znaménko mínus) podle data uvedení,
        # sekundárně vzestupně podle názvu
        ordering = ["-release_date", "title"]

    # Methods
    def __str__(self):
        """Součástí textové reprezentace filmu bude jeho název, rok uvedení a hodnocení"""
        return f"{self.title}, year: {str(self.release_date.year)}, rate: {str(self.rate)}"

    def get_absolute_url(self):
        """Metoda vrací URL stránky, na které se vypisují podrobné informace o filmu"""
        return reverse('film-detail', args=[str(self.id)])

    def release_year(self):
        return self.release_date.year

    def rate_percent(self):
        return format_html("{} %", int(self.rate * 10))


""" Třída Attachment je modelem pro databázový objekt (tabulku), který bude obsahovat údaje o přílohách filmů """
class Attachment(models.Model):
    # Fields
    # Povinný titulek přílohy - text do délky 200 znaků
    title = models.CharField(max_length=200, verbose_name="Title")
    # Časový údaj o poslední aktualizaci přílohy - automaticky se ukládá aktuální čas
    last_update = models.DateTimeField(auto_now=True)
    # Pole pro upload souboru
    # Parametr upload_to zajistí uložení souboru do složky specifikované v návratové hodnotě metody attachment_path
    file = models.FileField(upload_to=attachment_path, null=True, verbose_name="File")

    # Konstanta, v níž jsou ve formě n-tic (tuples) předdefinovány různé typy příloh
    TYPE_OF_ATTACHMENT = (
        ('audio', 'Audio'),
        ('image', 'Image'),
        ('text', 'Text'),
        ('video', 'Video'),
        ('other', 'Other'),
    )

    # Pole s definovanými předvolbami pro uložení typu přílohy
    type = models.CharField(max_length=5, choices=TYPE_OF_ATTACHMENT, blank=True, default='image', help_text='Select allowed attachment type', verbose_name="Attachment type")
    # Cizí klíč, který zajišťuje propojení přílohy s daným filmem (vztah N:1)
    # Parametr on_delete slouží k zajištění tzv. referenční integrity - v případě odstranění filmu
    # budou odstraněny i všechny jeho přílohy (models.CASCADE)
    film = models.ForeignKey(Film, on_delete=models.CASCADE)

    # Metadata
    class Meta:
        # Primární seřazeno podle poslední aktualizace souborů, sekundárně podle typu přílohy
        # ordering = ["-last_update", "type"]
        order_with_respect_to = 'film'

    # Methods
    def __str__(self):
        """ Textová reprezentace objektu """
        return f"{self.title}, ({self.type})"

    @property
    def filesize(self):
        x = self.file.size
        y = 512000
        if x < y * 1000:
            value = round(x / 1024, 2)
            ext = ' KB'
        elif x < y * 1000 ** 2:
            value = round(x / 1024 ** 2, 2)
            ext = ' MB'
        else:
            value = round(x / 1024 ** 3, 2)
            ext = ' GB'
        return str(value) + ext

movies/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from .models import Genre, Film


class FilmModelForm(ModelForm):
    def clean_runtime(self):
       data = self.cleaned_data['runtime']
       if data <= 0 or data > 1000:
           raise ValidationError('Neplatná délka filmu')
       return data

    def clean_rate(self):
       data = self.cleaned_data['rate']
       if data < 1 or data > 10:
           raise ValidationError('Neplatné hodnocení: musí být v rozsahu 1-10')
       return data

    class Meta:
        model = Film
        fields = ['title', 'plot', 'poster', 'genres', 'release_date', 'runtime', 'rate']
        labels = {'title': 'Název filmu', 'plot': 'Stručný děj'}

"""
class FilmForm(forms.Form):
    title = forms.CharField(label='Název filmu', help_text='Zadejte název filmu', required=True)
    plot = forms.CharField(label='Stručný děj', required=False)
    release_date = forms.DateField(label='Datum uvedení', required=True)
    runtime = forms.IntegerField(label='Délka filmu', required=False, help_text='Uveďte počet minut')
    poster = forms.ImageField(label='Plakát', required=False, help_text='Vkládejte grafické formáty')
    FILM_RATE = (
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
    )
    rate = forms.ChoiceField(choices=FILM_RATE, label='Hodnocení')
    genres = forms.ModelMultipleChoiceField(queryset = Genre.objects.all())
"""

movies/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView

from movies.forms import FilmModelForm
from movies.models import *

def index(request):
    """Metoda připravuje pohled pro domovskou stránku - šablona index.html"""

    # Uložení celkového počtu filmů v databázi do proměnné num_films
    num_films = Film.objects.all().count()
    # Do proměnné films se uloží 3 filmy uspořádané podle hodnocení (sestupně)
    films = Film.objects.order_by('-rate')[:3]

    """ Do proměnné context, která je typu slovník (dictionary) uložíme hodnoty obou proměnných """
    context = {
        'num_films': num_films,
        'films': films
    }

    """ Pomocí metody render vyrendrujeme šablonu index.html a předáme ji hodnoty v proměnné context k zobrazení """
    return render(request, 'index.html', context=context)


class FilmListView(ListView):
    model = Film

    context_object_name = 'film_list'
    template_name = 'film/list.html'
    paginate_by = 2

    def get_queryset(self):
        if 'genre_name' in self.kwargs:
            return Film.objects.filter(genres__name=self.kwargs['genre_name']).all() # Get 5 books containing the title war
        else:
            return Film.objects.all()

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['num_films'] = len(self.get_queryset())
        if 'genre_name' in self.kwargs:
            context['view_title'] = f"Žánr: {self.kwargs['genre_name']}"
            context['view_head'] = f"Žánr filmu: {self.kwargs['genre_name']}"
        else:
            context['view_title'] = 'Filmy'
            context['view_head'] = 'Přehled filmů'
        return context


class FilmDetailView(DetailView):
    model = Film

    context_object_name = 'film_detail'
    template_name = 'film/detail.html'


def topten(request):
    return render(request, 'topten.html')


class FilmCreateView(CreateView):
    model = Film
    fields = ['title', 'plot', 'poster', 'genres', 'release_date', 'runtime', 'rate']


class FilmUpdateView(UpdateView):
    model = Film
    template_name = 'movies/film_bootstrap_form.html'
    form_class = FilmModelForm


class FilmDeleteView(DeleteView):
    model = Film
    success_url = reverse_lazy('film_list')

movies/templates/base.html
<!DOCTYPE html>
<html lang="cs">
<head>
    <title>{% block title %}Filmotéka{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <!-- Add additional CSS in static file -->
    {% load static %}
    {% block css %}{% endblock %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    {% block header %} {% include "page/header.html" %} {% endblock %}
    {% block navbar %} {% include "page/navbar.html" %} {% endblock %}
<div class="container-fluid">
    {% block content %}{% endblock %}
</div>
{% block footer %} {% include "page/footer.html" %} {% endblock %}
<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<!-- Popper JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
{% block scripts %}{% endblock %}
</body>
</html>

movies/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  
  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>

<div class="container-fluid">

<div class="row">
  <div class="col-sm-2">
  {% block sidebar %}
  <ul class="sidebar-nav">
    <li><a href="{% url 'index' %}">Home</a></li>
    <li><a href="{% url 'books' %}">All books</a></li>
    <li><a href="{% url 'authors' %}">All authors</a></li>
  </ul>
 
  <ul class="sidebar-nav">
   {% if user.is_authenticated %}
     <li>User: {{ user.get_username }}</li>
     <li><a href="{% url 'my-borrowed' %}">My Borrowed</a></li>
     <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>   
   {% else %}
     <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>   
   {% endif %} 
  </ul>
  
   {% if user.is_staff %}
   <hr />
   <ul class="sidebar-nav">
   <li>Staff</li>
   {% if perms.catalog.can_mark_returned %}
   <li><a href="{% url 'all-borrowed' %}">All borrowed</a></li>
   {% endif %}
   </ul>
    {% endif %}
 
{% endblock %}
  </div>
  <div class="col-sm-10 ">
  {% block content %}{% endblock %}
  
  {% block pagination %}
    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
  {% endblock %} 
  
  
  </div>
</div>

</div>
</body>
</html>

movies/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="row mb-3">
    <div class="col-sm-12 bg-warning">
        <h2 class="display-4 text-center">Úvodní stránka</h2>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <h2 class="text-center bg-success text-light p-2">Filmové novinky</h2>
        {% include "blocks/new_films.html" %}
    </div>
    <div class="col-md-3">
        <h2 class="text-center bg-danger text-light p-2">Top deset filmů</h2>
        {% include "blocks/top_ten.html" %}
    </div>
    <div class="col-md-3">
        <h2 class="text-center bg-info text-light p-2">Filmové žánry</h2>
        {% include "blocks/genre_list.html" %}
    </div>
</div>
<div class="row">
</div>
{% endblock %}

movies/templates/topten.html
<!DOCTYPE html>
<html lang="cs">
<head>
    <meta charset="UTF-8">
    <title>Deset nej</title>
</head>
<body>
    <h1>Deset nejlepších filmů</h1>
</body>
</html>